// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | VideoBloksSlice
  | TextBlockSlice
  | GalleryBlockSlice
  | CtaBlockSlice
  | ContactFormSlice
  | SupportersSlice
  | ImageWithTextSlice
  | TestimonialsSlice
  | FeaturesSlice
  | TextImageOnBackgroundSlice
  | FilterSlice
  | VideoGallerySlice
  | TeamBlockSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlices1Slice = FooterSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.menu_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menu_image: prismic.ImageField<never>;

  /**
   * Menu Burger field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.menu_burger
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menu_burger: prismic.ImageField<never>;

  /**
   * Menu Close field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.menu_close
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menu_close: prismic.ImageField<never>
  /**
   * Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.name
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  name: prismic.KeyTextField;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Open details field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_details
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  open_details: prismic.KeyTextField;

  /**
   * Close details field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.close_details
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  close_details: prismic.KeyTextField;

  /**
   * Company field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * RegNr field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.regnr
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  regnr: prismic.KeyTextField;

  /**
   * Bank field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.bank
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bank: prismic.KeyTextField;

  /**
   * IBAN field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.iban
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iban: prismic.KeyTextField;

  /**
   * Copyright field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Privacy text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.privacy_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy_text: prismic.KeyTextField;

  /**
   * Privacy link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.privacy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_link: prismic.LinkField;

  /**
   * Bg Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.bg_image
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * Footer logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<SettingsDocumentDataSlices1Slice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *ContactForm → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Name Placeholder field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_placeholder: prismic.KeyTextField;

  /**
   * Email Placeholder field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Company field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Phone Placeholder field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.phone_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_placeholder: prismic.KeyTextField;

  /**
   * Text Placeholder field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.text_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_placeholder: prismic.KeyTextField;

  /**
   * Required field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.required
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  required: prismic.KeyTextField;

  /**
   * Checkbox text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.checkbox_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_text: prismic.KeyTextField;

  /**
   * Button text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Loading field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.loading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  loading: prismic.KeyTextField;

  /**
   * Sent title field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.sent_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sent_title: prismic.KeyTextField;

  /**
   * Sent text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.sent_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sent_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *CtaBlock → Primary*
 */
export interface CtaBlockSliceDefaultPrimary {
  /**
   * Section title field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Title 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * Image 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Text 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_1: prismic.KeyTextField;

  /**
   * Button text 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Title 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Image 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Text 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_2: prismic.KeyTextField;

  /**
   * Button text 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;
}

/**
 * Default variation for CtaBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CtaBlock → Primary*
 */
export interface CtaBlockSliceTabletFullWidthPrimary {
  /**
   * Section title field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Title 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * Image 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Text 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_1: prismic.KeyTextField;

  /**
   * Button text 1 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Title 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Image 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Text 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_2: prismic.KeyTextField;

  /**
   * Button text 2 field in *CtaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;
}

/**
 * Tablet full width variation for CtaBlock Slice
 *
 * - **API ID**: `tabletFullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSliceTabletFullWidth = prismic.SharedSliceVariation<
  "tabletFullWidth",
  Simplify<CtaBlockSliceTabletFullWidthPrimary>,
  never
>;

/**
 * Slice variation for *CtaBlock*
 */
type CtaBlockSliceVariation =
  | CtaBlockSliceDefault
  | CtaBlockSliceTabletFullWidth;

/**
 * CtaBlock Shared Slice
 *
 * - **API ID**: `cta_block`
 * - **Description**: CtaBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSlice = prismic.SharedSlice<
  "cta_block",
  CtaBlockSliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Image field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Image to left field in *Features → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: features.items[].image_to_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_to_left: prismic.BooleanField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *MapFilter → Primary*
 */
export interface FilterSliceDefaultPrimary {
  /**
   * First filter title field in *MapFilter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: First filter title
   * - **API ID Path**: filter.primary.filter_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  filter_1: prismic.KeyTextField;

  /**
   * Second filter title field in *MapFilter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Second filter title
   * - **API ID Path**: filter.primary.filter_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  filter_2: prismic.KeyTextField;

  /**
   * Filter placeholder field in *MapFilter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.filter_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  filter_placeholder: prismic.KeyTextField;

  /**
   * Pin field in *MapFilter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.pin
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pin: prismic.ImageField<never>;

  /**
   * Active pin field in *MapFilter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.active_pin
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  active_pin: prismic.ImageField<never>;

  /**
   * Open field in *MapFilter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.open
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  open: prismic.ImageField<never>;

  /**
   * Logo placeholder field in *MapFilter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.logo_placeholder
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_placeholder: prismic.ImageField<never>;

  /**
   * Alert message field in *MapFilter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.primary.alert_message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  alert_message: prismic.KeyTextField;
}

/**
 * Primary content in *MapFilter → Items*
 */
export interface FilterSliceDefaultItem {
  /**
   * Logo field in *MapFilter → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Phone field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Phone second field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional
   * - **API ID Path**: filter.items[].phone_second
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_second: prismic.KeyTextField;

  /**
   * Email field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Address field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Geolocation field in *MapFilter → Items*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: filter.items[].geolocation
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  geolocation: prismic.GeoPointField;

  /**
   * First filter option field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional
   * - **API ID Path**: filter.items[].first_filter_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_filter_option: prismic.KeyTextField;

  /**
   * Second filter option field in *MapFilter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional
   * - **API ID Path**: filter.items[].second_filter_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_filter_option: prismic.KeyTextField;
}

/**
 * Default variation for MapFilter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FilterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FilterSliceDefaultPrimary>,
  Simplify<FilterSliceDefaultItem>
>;

/**
 * Slice variation for *MapFilter*
 */
type FilterSliceVariation = FilterSliceDefault;

/**
 * MapFilter Shared Slice
 *
 * - **API ID**: `filter`
 * - **Description**: Filter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FilterSlice = prismic.SharedSlice<"filter", FilterSliceVariation>;

/**
 * Primary content in *FooterSocials → Items*
 */
export interface FooterSliceDefaultItem {
  /**
   * Social icon field in *FooterSocials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.items[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Social link field in *FooterSocials → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.items[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField;
}

/**
 * Default variation for FooterSocials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FooterSliceDefaultItem>
>;

/**
 * Slice variation for *FooterSocials*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * FooterSocials Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *GalleryBlock → Primary*
 */
export interface GalleryBlockSliceDefaultPrimary {
  /**
   * Image 1 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * TopRippedImg field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.toprippedimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  toprippedimg: prismic.ImageField<never>;

  /**
   * BottomRippedImg field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.bottomrippedimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bottomrippedimg: prismic.ImageField<never>;
}

/**
 * Default variation for GalleryBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *GalleryBlock → Primary*
 */
export interface GalleryBlockSliceDoubleToLeftPrimary {
  /**
   * Image 1 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * TopRippedImg field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.toprippedimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  toprippedimg: prismic.ImageField<never>;

  /**
   * BottomRippedImg field in *GalleryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.primary.bottomrippedimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bottomrippedimg: prismic.ImageField<never>;
}

/**
 * Double to left variation for GalleryBlock Slice
 *
 * - **API ID**: `doubleToLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSliceDoubleToLeft = prismic.SharedSliceVariation<
  "doubleToLeft",
  Simplify<GalleryBlockSliceDoubleToLeftPrimary>,
  never
>;

/**
 * Slice variation for *GalleryBlock*
 */
type GalleryBlockSliceVariation =
  | GalleryBlockSliceDefault
  | GalleryBlockSliceDoubleToLeft;

/**
 * GalleryBlock Shared Slice
 *
 * - **API ID**: `gallery_block`
 * - **Description**: GalleryBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSlice = prismic.SharedSlice<
  "gallery_block",
  GalleryBlockSliceVariation
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Mobile image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_image: prismic.ImageField<never>;

  /**
   * Text field in *ImageWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Top Ripped Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.top_ripped_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  top_ripped_image: prismic.ImageField<never>;

  /**
   * Bottom Ripped Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.bottom_ripped_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bottom_ripped_image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation = ImageWithTextSliceDefault;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *Supporters → Primary*
 */
export interface SupportersSliceDefaultPrimary {
  /**
   * Title field in *Supporters → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image 1 field in *Supporters → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Supporters → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Supporters → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Supporters → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Bg image field in *Supporters → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: supporters.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;
}

/**
 * Default variation for Supporters Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SupportersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SupportersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Supporters*
 */
type SupportersSliceVariation = SupportersSliceDefault;

/**
 * Supporters Shared Slice
 *
 * - **API ID**: `supporters`
 * - **Description**: Supporters
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SupportersSlice = prismic.SharedSlice<
  "supporters",
  SupportersSliceVariation
>;

/**
 * Primary content in *TeamBlock → Items*
 */
export interface TeamBlockSliceDefaultItem {
  /**
   * Image field in *TeamBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Text field in *TeamBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_block.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for TeamBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TeamBlockSliceDefaultItem>
>;

/**
 * Slice variation for *TeamBlock*
 */
type TeamBlockSliceVariation = TeamBlockSliceDefault;

/**
 * TeamBlock Shared Slice
 *
 * - **API ID**: `team_block`
 * - **Description**: TeamBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamBlockSlice = prismic.SharedSlice<
  "team_block",
  TeamBlockSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Button field in *Testimonials → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.button
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  button: prismic.ImageField<never>;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Company field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Text field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Title field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *TextImageOnBackground → Primary*
 */
export interface TextImageOnBackgroundSliceDefaultPrimary {
  /**
   * Image field in *TextImageOnBackground → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_on_background.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *TextImageOnBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_on_background.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Bg image field in *TextImageOnBackground → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_on_background.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;
}

/**
 * Default variation for TextImageOnBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageOnBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageOnBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextImageOnBackground*
 */
type TextImageOnBackgroundSliceVariation = TextImageOnBackgroundSliceDefault;

/**
 * TextImageOnBackground Shared Slice
 *
 * - **API ID**: `text_image_on_background`
 * - **Description**: TextImageOnBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageOnBackgroundSlice = prismic.SharedSlice<
  "text_image_on_background",
  TextImageOnBackgroundSliceVariation
>;

/**
 * Primary content in *VideoBloks → Primary*
 */
export interface VideoBloksSliceDefaultPrimary {
  /**
   * Title field in *VideoBloks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_bloks.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * VideoImage field in *VideoBloks → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_bloks.primary.videoimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  videoimage: prismic.ImageField<never>;

  /**
   * PlayImage field in *VideoBloks → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_bloks.primary.playimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  playimage: prismic.ImageField<never>;

  /**
   * Video field in *VideoBloks → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video_bloks.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Default variation for VideoBloks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBloksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBloksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBloks*
 */
type VideoBloksSliceVariation = VideoBloksSliceDefault;

/**
 * VideoBloks Shared Slice
 *
 * - **API ID**: `video_bloks`
 * - **Description**: VideoBloks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBloksSlice = prismic.SharedSlice<
  "video_bloks",
  VideoBloksSliceVariation
>;

/**
 * Primary content in *VideoGallery → Primary*
 */
export interface VideoGallerySliceDefaultPrimary {
  /**
   * Image bg field in *VideoGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.primary.image_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_bg: prismic.ImageField<never>;

  /**
   * Last element text field in *VideoGallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.primary.last_element_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_element_text: prismic.KeyTextField;

  /**
   * Load more field in *VideoGallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.primary.load_more
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  load_more: prismic.KeyTextField;

  /**
   * Play Image field in *VideoGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.primary.playimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  playimage: prismic.ImageField<never>;

  /**
   * Video Close field in *VideoGallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.primary.videoClose
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  videoClose: prismic.ImageField<never>;
}

/**
 * Primary content in *VideoGallery → Items*
 */
export interface VideoGallerySliceDefaultItem {
  /**
   * Name field in *VideoGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Video field in *VideoGallery → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Image field in *VideoGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for VideoGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoGallerySliceDefaultPrimary>,
  Simplify<VideoGallerySliceDefaultItem>
>;

/**
 * Slice variation for *VideoGallery*
 */
type VideoGallerySliceVariation = VideoGallerySliceDefault;

/**
 * VideoGallery Shared Slice
 *
 * - **API ID**: `video_gallery`
 * - **Description**: VideoGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoGallerySlice = prismic.SharedSlice<
  "video_gallery",
  VideoGallerySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      PageDocument,
      PageDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CtaBlockSlice,
      CtaBlockSliceVariation,
      CtaBlockSliceDefault,
      CtaBlockSliceTabletFullWidth,
      FeaturesSlice,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FilterSlice,
      FilterSliceVariation,
      FilterSliceDefault,
      FooterSlice,
      FooterSliceVariation,
      FooterSliceDefault,
      GalleryBlockSlice,
      GalleryBlockSliceVariation,
      GalleryBlockSliceDefault,
      GalleryBlockSliceDoubleToLeft,
      ImageWithTextSlice,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      SupportersSlice,
      SupportersSliceVariation,
      SupportersSliceDefault,
      TeamBlockSlice,
      TeamBlockSliceVariation,
      TeamBlockSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextBlockSlice,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextImageOnBackgroundSlice,
      TextImageOnBackgroundSliceVariation,
      TextImageOnBackgroundSliceDefault,
      VideoBloksSlice,
      VideoBloksSliceVariation,
      VideoBloksSliceDefault,
      VideoGallerySlice,
      VideoGallerySliceVariation,
      VideoGallerySliceDefault,
    };
  }
}
