// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  cta_block: dynamic(() => import("./CtaBlock")),
  features: dynamic(() => import("./Features")),
  filter: dynamic(() => import("./Filter")),
  footer: dynamic(() => import("./FooterSocials")),
  gallery_block: dynamic(() => import("./GalleryBlock")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  supporters: dynamic(() => import("./Supporters")),
  team_block: dynamic(() => import("./TeamBlock")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_block: dynamic(() => import("./TextBlock")),
  text_image_on_background: dynamic(() => import("./TextImageOnBackground")),
  video_bloks: dynamic(() => import("./VideoBloks")),
  video_gallery: dynamic(() => import("./VideoGallery")),
};
